### PR TITLE
Paraplegic user docs

### PR DESCRIPTION
**Pull request by ParaplegicRacehorse**
__ **NOT READY FOR ACCEPT / MERGE** __

;; This is for beginning a discussion. Files are in far too-early stage to move into the `burtonator/` tree. 
;; If this _does_ somehow get merged, I would personally prefer it go into a separate branch to keep
;; `master` uncluttered.

;; a beginning of a fix to #126 

-----

I made an early start on a user manual, mostly by copy-paste from the Documentation web pages. It turns out those pages are mostly worthless as documentation, though they make good start on an Intro chapter and pair of indexes.

Let's talk about how/where I go digging in code to find in-source documentation, if any, and how a non-programmer can recognize it. We can also talk about acceptable-use of what's already here, including what I'd like to get right from `burtonator/master` root `REAMDE.md`.

### CODE REVIEW

**Comment by burtonator** [comment]
cool... 

There's a dedicated git repo for the site:

https://github.com/burtonator/polar-site

There is a 'docs' dir and I just haven't had time to update it yet.

**Comment by ParaplegicRacehorse** [comment]
That repository is 404. Do you mean 

Https://github.com/burtonator/polar-docs ?

I don't know my markdown well at all and I hesitate to install anything node-based because it's a system resource hog par-excellance. However, org let's me export markdown and git is simple enough even for me. :)

Now, how do I find the in-code documentation? I haven't looked yet. Is it all in comments?

**Comment by burtonator** [comment]
Ah... sorry.  That repo is private.  Let me verify that I can open it but pretty sure I can... I think I intended it to be open.

**Comment by k1ckk** [comment]
@burtonator any updates on this?

**Pull request closed without merging**
