### PR TITLE
Change item's title on click

### PR DESCRIPTION
**Pull request by btcrs**
**The issue:** 
renaming items ( especially in bulk ) was tedious. I suspected a reason was simply the number of clicks needed to rename an item.

**The Proposed Solution:**
Make the title field editable, and save on blur.

screen recording 2018-10-24 at 10 48 22 pm 2018-10-24 23_01_01

### CODE REVIEW

**Comment by burtonator** [comment]
This is awesome and was sort of what I was thinking about early on but how does this work with double click?

**Comment by burtonator** [comment]
Curious about this commit.. It looks like you edited the compiled .js file and copied it on to the .tsx file?

We would need to refactor this to see what the actual commit looks like.

**Comment by btcrs** [comment]
Ahh, sorry about that. It was my very groggy first attempt at getting into this! Should be fixed now.

My first thought about handling double click was simply to blur the event target on the double click event. This doesn't seamlessly handle an accidental double click or when the double click occurs after the title has focus. It has the potential to leave the title in an edit state after opening the target.

I'll look a little further into this to see if it's avoidable or not.

screen recording 2018-10-25 at 1 13 41 am 2018-10-25 01_46_07

**Comment by burtonator** [comment]
I can't really think of an easy way to handle this.. maybe impolement a context menu and then have right click and then edit inline there?

**Comment by btcrs** [comment]
that could be done, though my goal was really to flatten out the UX, so that the renaming wasn't hidden in a deeper level. I think a context menu would probably not change much about the action of renaming.

I made some changes so that a double click will always act as it did before. Any single click to the title column would prompt an editable value and any double click will open the document and end ongoing edits.

Is the concern that it isn't possible to select a row by clicking on the title column without prompting an edit?

**Comment by burtonator** [comment]
I think my concerns are right click (though that's easily handled) not triggering the edit.

But also single click, now , selects the current item. My plan was to have a sidebar nav refresh with metadata about the file (when it's toggled open).

I was going to put a thumbnail/image for the post as well as metadata there.  This would prevent that...

I do really like the concept of single click edit as I've seen this done successfully in a lot of UIs.

Maybe we could do long single click???  Thinking out loud here.  Are there any other UIs that do this that I could look at that you were inspired from?

**Comment by btcrs** [comment]
Gotcha, totally understand. I haven't looked into any similar UIs, so I'm just going off what feels the most natural as a user at this point.

I've refactored the feature to edit on right click. I think it feels pretty good once you figure out that right click is the trigger and it still only takes one click. The only issue with this solution is that it prevents a context menu being added to the title column. I don't see this as being a big issue, but if it conflicts with anything else in the roadmap I think there are two other directions.

modifier-click: in this case single clicking the title with a modifier key would trigger edit. The main cons are that it requires the knowledge of the trigger and it takes two hands. However, it frees up the context menu. This would be a small change to the current refactor that could be done later.

inline icon: a small icon (likely pencil ) in the title column would trigger edit. This is obvious to the user and pretty simple to use. It does add a lot of clutter to the ui and would be duplicated on every row, which is pretty unnecessary.

**Comment by Lennart-J** [comment]
Hey, just my 2 cents: I personally use F2 quite a lot to rename files, adding this as an extra option would be sweet.

**Comment by burtonator** [comment]
@Lennart-J 

F2 on what platform?

**Comment by Lennart-J** [comment]
Mostly Windows, seems to be fairly common on Linux, too

**Comment by klausondrag** [comment]
F2 is a very common shortcut for renaming As an alternative to a right-click menu you can blend in icons on hover at the end of the column, like in the new Gmail interface. This could also be used for editing Tags.

**Pull request closed without merging**
