### PR TITLE
Setup TypedTags to allow / for hierarchical tags.

### PR DESCRIPTION
**Pull request by adamwolf**
Use hierarchical tags for Anki subdecks.  Add to README.  Add tests.

@burtonator please note I do not know Javascript or TypeScript well, so I may have made egregious mistakes. On the other hand, it appears to work for me.  I can sync into an Anki subdeck.  Feel free to accept or modify or reject--I won't be offended regardless.  Thanks for all your hard work.

### CODE REVIEW

**Comment by burtonator** [comment]
Thanks.. looks pretty good and I will try to merge soon.

**Comment by burtonator** [comment]
Hey.. looks good.  Could we make one change?

I don't want to change the tag value from ```string``` to ```string[]``` 

Instead what we can do is replace the "/" to "::" as part of computing the deck name. 

Should be a simple replacement.

I'd like that tag value to be mostly opaque. 

I can also fix when I get around to it too but might be a day or two.

**Comment by adamwolf** [comment]
Yeah, I can't get it it for a day or two so it'll be a race :) I'll post in
here when I can get to it again.

**Comment by adamwolf** [comment]
Updated.  LMK how it looks.

If you could point me to an example where you test with a DocInfo, I could setup tests for computeDeckName() as well.

**Comment by adamwolf** [comment]
Something isn't right with this right now.  I will try to debug.

**Comment by adamwolf** [comment]
There we go.  Works for me.

**Pull request merged**
